#You must include this additional source as the BlinkEReceipt pod is hosted in a private spec repository
source 'https://github.com/BlinkReceipt/PodSpecRepo.git'
source 'https://cdn.cocoapods.org/'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'SampleApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'BlinkEReceipt'
  pod 'BlinkReceipt'
	
  target 'SampleAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'SampleApp-tvOS' do
  # Pods for SampleApp-tvOS

  target 'SampleApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
